# Dependencies
markdown:            kramdown
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Randy Ridenour
tagline:             
description:         
url:                 http://randyridenour.net
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Randy Ridenour
  url:               https://twitter.com/randyridenour
  email:             rlridenour@gmail.com

# CSS
sass:
  sass_dir: _sass
  style: :compressed

# Prose.io
prose:
  siteurl: "http://randyridenour.net"
  media: "images"
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
          - name: "comments"
        field:
          label: "Comments"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          label: "Layout"
          element: "text"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "Post Title"
          
# Custom vars
version:             1.0.0
